// AUTO-GENERATED by scripts/split-interactive-map.js — do not edit.
export const map: Record<string, () => Promise<any>> = {
  "ayanamsha-choice-verifier": () => import("./ayanamsha-choice-verifier/index"),
  "birth-time-accuracy-assessment": () => import("./birth-time-accuracy-assessment/index"),
  "convergence-divergence-workbench": () => import("./convergence-divergence-workbench/index"),
  "cross-check-decision-synthesizer": () => import("./cross-check-decision-synthesizer/index"),
  "cross-stream-concept-builder": () => import("./cross-stream-concept-builder/index"),
  "dasha-context-analyzer": () => import("./dasha-context-analyzer/index"),
  "data-preparation-preflight": () => import("./data-preparation-preflight/index"),
  "dignity-strength-analyzer": () => import("./dignity-strength-analyzer/index"),
  "house-system-choice-verifier": () => import("./house-system-choice-verifier/index"),
  "parashari-kp-verifier": () => import("./parashari-kp-verifier/index"),
  "preliminary-cross-check-preflight": () => import("./preliminary-cross-check-preflight/index"),
  "reading-documentation-template": () => import("./reading-documentation-template/index"),
  "reading-synthesis-workbench": () => import("./reading-synthesis-workbench/index"),
  "tattva-shuddhi-checker": () => import("./tattva-shuddhi-checker/index"),
  "transit-context-analyzer": () => import("./transit-context-analyzer/index"),
  "yoga-dosha-identifier": () => import("./yoga-dosha-identifier/index"),
};
