// AUTO-GENERATED by scripts/split-interactive-map.js — do not edit.
export const map: Record<string, () => Promise<any>> = {
  "cross-stream-property-synthesis-lab": () => import("./cross-stream-property-synthesis-lab/index"),
  "d4-complete-property-reading-assembly-lab": () => import("./d4-complete-property-reading-assembly-lab/index"),
  "d4-construction-workbench": () => import("./d4-construction-workbench/index"),
  "d4-internal-lagna-fourth-reading-lab": () => import("./d4-internal-lagna-fourth-reading-lab/index"),
  "d4-property-quality-comparison-lab": () => import("./d4-property-quality-comparison-lab/index"),
  "fourth-house-property-workbench": () => import("./fourth-house-property-workbench/index"),
  "fourth-lord-property-permutation-lab": () => import("./fourth-lord-property-permutation-lab/index"),
  "home-purchase-confidence-synthesis-lab": () => import("./home-purchase-confidence-synthesis-lab/index"),
  "kp-property-fourth-cusp-sub-lord-lab": () => import("./kp-property-fourth-cusp-sub-lord-lab/index"),
  "kp-property-significator-timing-lab": () => import("./kp-property-significator-timing-lab/index"),
  "lal-kitab-property-teva-formula-lab": () => import("./lal-kitab-property-teva-formula-lab/index"),
  "mars-property-karaka-depth-lab": () => import("./mars-property-karaka-depth-lab/index"),
  "property-competence-routing-lab": () => import("./property-competence-routing-lab/index"),
  "property-dasha-acquisition-timing-lab": () => import("./property-dasha-acquisition-timing-lab/index"),
  "secondary-property-indicators-synthesis-lab": () => import("./secondary-property-indicators-synthesis-lab/index"),
  "vastu-property-scope-distinction-lab": () => import("./vastu-property-scope-distinction-lab/index"),
};
