// AUTO-GENERATED by scripts/split-interactive-map.js — do not edit.
export const map: Record<string, () => Promise<any>> = {
  "angular-house-classifier": () => import("./angular-house-classifier/index"),
  "bhava-chalita-refinement": () => import("./bhava-chalita-refinement/index"),
  "bhava-madhya-sandhi": () => import("./bhava-madhya-sandhi/index"),
  "bhava-profile": () => import("./bhava-profile/index"),
  "bhava-template-card": () => import("./bhava-template-card/index"),
  "bhava-wheel": () => import("./bhava-wheel/index"),
  "bhavat-bhavam-drill": () => import("./bhavat-bhavam-drill/index"),
  "house-system-comparator": () => import("./house-system-comparator/index"),
  "house-system-decision-framework": () => import("./house-system-decision-framework/index"),
  "karaka-table": () => import("./karaka-table/index"),
  "karaka-tenancy-lab": () => import("./karaka-tenancy-lab/index"),
  "lal-kitab-fixed-aries-lagna": () => import("./lal-kitab-fixed-aries-lagna/index"),
  "placidus-kp-convention": () => import("./placidus-kp-convention/index"),
  "preliminary-reading-flow": () => import("./preliminary-reading-flow/index"),
  "purushartha-trine-explorer": () => import("./purushartha-trine-explorer/index"),
  "quality-house-classifier": () => import("./quality-house-classifier/index"),
};
