import dynamic from "next/dynamic";

export const REGISTRY = {
  "d60-karmic-substrate-index-lab": dynamic(() => import("../d60-karmic-substrate-index-lab").then(m => ({ default: m.D60KarmicSubstrateIndexLab }))),
  "d60-spiritual-path-arc-lab": dynamic(() => import("../d60-spiritual-path-arc-lab").then(m => ({ default: m.D60SpiritualPathArcLab }))),
  "d60-honest-framing-ethics-lab": dynamic(() => import("../d60-honest-framing-ethics-lab").then(m => ({ default: m.D60HonestFramingEthicsLab }))),
  "d60-worked-reading-confidence-lab": dynamic(() => import("../d60-worked-reading-confidence-lab").then(m => ({ default: m.D60WorkedReadingConfidenceLab }))),
  "d1-d9-divergence-reader": dynamic(() => import("../d1-d9-divergence-reader").then(m => ({ default: m.D1D9DivergenceReader }))),
  "d7-jupiter-karaka-workbench": dynamic(() => import("../d7-jupiter-karaka-workbench").then(m => ({ default: m.D7JupiterKarakaWorkbench }))),
  "d7-santana-protocol-runner": dynamic(() => import("../d7-santana-protocol-runner").then(m => ({ default: m.D7SantanaProtocolRunner }))),
  "dasha-timing-foreign-settlement-sweep": dynamic(() => import("../dasha-timing-foreign-settlement-sweep").then(m => ({ default: m.DashaTimingForeignSettlementSweep }))),
  "dasha-conflict-timing-sweep": dynamic(() => import("../dasha-conflict-timing-sweep").then(m => ({ default: m.DashaConflictTimingSweep }))),
  "divergence-pattern-ranker": dynamic(() => import("../divergence-pattern-ranker").then(m => ({ default: m.DivergencePatternRanker }))),
  "dual-matrix-domain-comparison": dynamic(() => import("../dual-matrix-domain-comparison").then(m => ({ default: m.DualMatrixDomainComparison }))),
  "death-prediction-prohibition-trainer": dynamic(() => import("../death-prediction-prohibition-trainer").then(m => ({ default: m.DeathPredictionProhibitionTrainer }))),
  "d24-construction-workbench": dynamic(() => import("../d24-construction-workbench").then(m => ({ default: m.D24ConstructionWorkbench }))),
  "d24-education-reading-workbench": dynamic(() => import("../d24-education-reading-workbench").then(m => ({ default: m.D24EducationReadingWorkbench }))),
  "d24-mercury-jupiter-karaka-workbench": dynamic(() => import("../d24-mercury-jupiter-karaka-workbench").then(m => ({ default: m.D24MercuryJupiterKarakaWorkbench }))),
  "d24-education-synthesis-workbench": dynamic(() => import("../d24-education-synthesis-workbench").then(m => ({ default: m.D24EducationSynthesisWorkbench }))),
  "d4-construction-workbench": dynamic(() => import("../d4-construction-workbench").then(m => ({ default: m.D4ConstructionWorkbench }))),
  "d4-internal-lagna-fourth-reading-lab": dynamic(() => import("../d4-internal-lagna-fourth-reading-lab").then(m => ({ default: m.D4InternalLagnaFourthReadingLab }))),
  "d4-property-quality-comparison-lab": dynamic(() => import("../d4-property-quality-comparison-lab").then(m => ({ default: m.D4PropertyQualityComparisonLab }))),
  "d4-complete-property-reading-assembly-lab": dynamic(() => import("../d4-complete-property-reading-assembly-lab").then(m => ({ default: m.D4CompletePropertyReadingAssemblyLab }))),
  "d2-solar-lunar-bisection": dynamic(() => import("../d2-solar-lunar-bisection").then(m => ({ default: m.D2SolarLunarBisection }))),
  "d2-bisection-doctrine-reader": dynamic(() => import("../d2-bisection-doctrine-reader").then(m => ({ default: m.D2BisectionDoctrineReader }))),
  "d2-solar-lunar-tendencies": dynamic(() => import("../d2-solar-lunar-tendencies").then(m => ({ default: m.D2SolarLunarTendencies }))),
  "d2-real-chart-workbench": dynamic(() => import("../d2-real-chart-workbench").then(m => ({ default: m.D2RealChartWorkbench }))),
  "dhana-yoga-pattern-verifier": dynamic(() => import("../dhana-yoga-pattern-verifier").then(m => ({ default: m.DhanaYogaPatternVerifier }))),
  "dhana-yoga-variants-evaluator": dynamic(() => import("../dhana-yoga-variants-evaluator").then(m => ({ default: m.DhanaYogaVariantsEvaluator }))),
  "dhana-yoga-shadbala-overlay": dynamic(() => import("../dhana-yoga-shadbala-overlay").then(m => ({ default: m.DhanaYogaShadbalaOverlay }))),
  "dashamsha-deva-asura-lab": dynamic(() => import("../dashamsha-deva-asura-lab").then(m => ({ default: m.DashamshaDevaAsuraLab }))),
  "d9-marriage-refinement-workbench": dynamic(() => import("../d9-marriage-refinement-workbench").then(m => ({ default: m.D9MarriageRefinementWorkbench }))),
  "d9-lagna-seventh-reader": dynamic(() => import("../d9-lagna-seventh-reader").then(m => ({ default: m.D9LagnaSeventhReader }))),
  "d9-venus-karaka-workbench": dynamic(() => import("../d9-venus-karaka-workbench").then(m => ({ default: m.D9VenusKarakaWorkbench }))),
  "d9-marriage-worked-example-lab": dynamic(() => import("../d9-marriage-worked-example-lab").then(m => ({ default: m.D9MarriageWorkedExampleLab }))),
  "darakaraka-spouse-register-workbench": dynamic(() => import("../darakaraka-spouse-register-workbench").then(m => ({ default: m.DarakarakaSpouseRegisterWorkbench }))),
  "d20-vimshamsha-construction-lab": dynamic(() => import("../d20-vimshamsha-construction-lab").then(m => ({ default: m.D20VimshamshaConstructionLab }))),
  "d20-lagna-spiritual-houses-lab": dynamic(() => import("../d20-lagna-spiritual-houses-lab").then(m => ({ default: m.D20LagnaSpiritualHousesLab }))),
  "d20-spiritual-karakas-overlay-lab": dynamic(() => import("../d20-spiritual-karakas-overlay-lab").then(m => ({ default: m.D20SpiritualKarakasOverlayLab }))),
  "d20-spiritual-reading-synthesis-lab": dynamic(() => import("../d20-spiritual-reading-synthesis-lab").then(m => ({ default: m.D20SpiritualReadingSynthesisLab }))),
};
