import dynamic from "next/dynamic";

export const REGISTRY = {
  "nakshatras-categorized-explorer": dynamic(() => import("../nakshatras-categorized-explorer").then(m => ({ default: m.NakshatrasCategorizedExplorer }))),
  "numerology-system-selection": dynamic(() => import("../numerology-system-selection").then(m => ({ default: m.NumerologySystemSelection }))),
  "navamsha-calculator": dynamic(() => import("../navamsha-calculator").then(m => ({ default: m.NavamshaCalculator }))),
  "navamsha-reader": dynamic(() => import("../navamsha-reader").then(m => ({ default: m.NavamshaReader }))),
  "ninth-house-chart-t1-explorer": dynamic(() => import("../ninth-house-chart-t1-explorer").then(m => ({ default: m.NinthHouseChartT1Explorer }))),
  "nri-yoga-citation-honesty-explorer": dynamic(() => import("../nri-yoga-citation-honesty-explorer").then(m => ({ default: m.NriYogaCitationHonestyExplorer }))),
  "nri-yoga-pattern-spotter": dynamic(() => import("../nri-yoga-pattern-spotter").then(m => ({ default: m.NriYogaPatternSpotter }))),
  "naisargika-ayur-cross-check-workbench": dynamic(() => import("../naisargika-ayur-cross-check-workbench").then(m => ({ default: m.NaisargikaAyurCrossCheckWorkbench }))),
  "nakshatra-profile": dynamic(() => import("../nakshatra-profile").then(m => ({ default: m.NakshatraProfile }))),
  "nakshatra-template-lab": dynamic(() => import("../nakshatra-template-lab").then(m => ({ default: m.NakshatraTemplateLab }))),
  "naisargika-table": dynamic(() => import("../naisargika-table").then(m => ({ default: m.NaisargikaTable }))),
  "naisargika-rationale": dynamic(() => import("../naisargika-rationale").then(m => ({ default: m.NaisargikaRationale }))),
  "neecha-bhanga-checker": dynamic(() => import("../neecha-bhanga-checker").then(m => ({ default: m.NeechaBhangaChecker }))),
  "name-correction-rationale-evaluator": dynamic(() => import("../name-correction-rationale-evaluator").then(m => ({ default: m.NameCorrectionRationaleEvaluator }))),
  "name-correction-candidate-calculator": dynamic(() => import("../name-correction-candidate-calculator").then(m => ({ default: m.NameCorrectionCandidateCalculator }))),
  "name-correction-caution-screener": dynamic(() => import("../name-correction-caution-screener").then(m => ({ default: m.NameCorrectionCautionScreener }))),
  "numerology-honest-handling-inspector": dynamic(() => import("../numerology-honest-handling-inspector").then(m => ({ default: m.NumerologyHonestHandlingInspector }))),
  "numerology-compatibility-calculator": dynamic(() => import("../numerology-compatibility-calculator").then(m => ({ default: m.NumerologyCompatibilityCalculator }))),
  "numerology-decision-flow": dynamic(() => import("../numerology-decision-flow").then(m => ({ default: m.NumerologyDecisionFlow }))),
  "nadi-discipline-statement-builder": dynamic(() => import("../nadi-discipline-statement-builder").then(m => ({ default: m.NadiDisciplineStatementBuilder }))),
  "nadi-access-limits-decision-lab": dynamic(() => import("../nadi-access-limits-decision-lab").then(m => ({ default: m.NadiAccessLimitsDecisionLab }))),
  "ninth-house-higher-learning-workbench": dynamic(() => import("../ninth-house-higher-learning-workbench").then(m => ({ default: m.NinthHouseHigherLearningWorkbench }))),
  "natural-wealth-karaka-analyzer": dynamic(() => import("../natural-wealth-karaka-analyzer").then(m => ({ default: m.NaturalWealthKarakaAnalyzer }))),
  "natal-relative-counter": dynamic(() => import("../natal-relative-counter").then(m => ({ default: m.NatalRelativeCounter }))),
  "nodal-transit-tracker": dynamic(() => import("../nodal-transit-tracker").then(m => ({ default: m.NodalTransitTracker }))),
  "nodal-axis-house-reader": dynamic(() => import("../nodal-axis-house-reader").then(m => ({ default: m.NodalAxisHouseReader }))),
  "navaratna-table": dynamic(() => import("../navaratna-table").then(m => ({ default: m.NavaratnaTable }))),
  "nadi-verification-sandbox": dynamic(() => import("../nadi-verification-sandbox").then(m => ({ default: m.NadiVerificationSandbox }))),
  "nadi-commercial-explorer": dynamic(() => import("../nadi-commercial-explorer").then(m => ({ default: m.NadiCommercialExplorer }))),
  "nadi-decision-framework": dynamic(() => import("../nadi-decision-framework").then(m => ({ default: m.NadiDecisionFramework }))),
  "nadi-honest-handling-instance": dynamic(() => import("../nadi-honest-handling-instance").then(m => ({ default: m.NadiHonestHandlingInstance }))),
};
