import dynamic from "next/dynamic";

export const REGISTRY = {
  "kendra-trikona-grouping-visualizer": dynamic(() => import("../kendra-trikona-grouping-visualizer").then(m => ({ default: m.KendraTrikonaGroupingVisualizer }))),
  "kp-children-cusp-tool": dynamic(() => import("../kp-children-cusp-tool").then(m => ({ default: m.KpChildrenCuspTool }))),
  "kp-children-significator-timing-bench": dynamic(() => import("../kp-children-significator-timing-bench").then(m => ({ default: m.KpChildrenSignificatorTimingBench }))),
  "kp-foreign-travel-cusp-tool": dynamic(() => import("../kp-foreign-travel-cusp-tool").then(m => ({ default: m.KpForeignTravelCuspTool }))),
  "kp-litigation-cusp-tool": dynamic(() => import("../kp-litigation-cusp-tool").then(m => ({ default: m.KpLitigationCuspTool }))),
  "kp-shared-significator-explorer": dynamic(() => import("../kp-shared-significator-explorer").then(m => ({ default: m.KpSharedSignificatorExplorer }))),
  "kp-case-outcome-horary-intro": dynamic(() => import("../kp-case-outcome-horary-intro").then(m => ({ default: m.KpCaseOutcomeHoraryIntro }))),
  "kp-litigation-synthesis-workbench": dynamic(() => import("../kp-litigation-synthesis-workbench").then(m => ({ default: m.KpLitigationSynthesisWorkbench }))),
  "kp-longevity-doctrine-explorer": dynamic(() => import("../kp-longevity-doctrine-explorer").then(m => ({ default: m.KpLongevityDoctrineExplorer }))),
  "kp-sub-calculator": dynamic(() => import("../kp-sub-calculator").then(m => ({ default: m.KpSubCalculator }))),
  "karakamsha-virgo-soul-map-lab": dynamic(() => import("../karakamsha-virgo-soul-map-lab").then(m => ({ default: m.KarakamshaVirgoSoulMapLab }))),
  "karakamsha-ishta-synthesis-walkthrough": dynamic(() => import("../karakamsha-ishta-synthesis-walkthrough").then(m => ({ default: m.KarakamshaIshtaSynthesisWalkthrough }))),
  "kp-cuspal-yes-no-augmentation-lab": dynamic(() => import("../kp-cuspal-yes-no-augmentation-lab").then(m => ({ default: m.KpCuspalYesNoAugmentationLab }))),
  "kp-purpose-built-routing-lab": dynamic(() => import("../kp-purpose-built-routing-lab").then(m => ({ default: m.KpPurposeBuiltRoutingLab }))),
  "kp-layer-boundary-worked-example-lab": dynamic(() => import("../kp-layer-boundary-worked-example-lab").then(m => ({ default: m.KpLayerBoundaryWorkedExampleLab }))),
  "kp-longevity-chart-h1-synthesis": dynamic(() => import("../kp-longevity-chart-h1-synthesis").then(m => ({ default: m.KpLongevityChartH1Synthesis }))),
  "kalapurusha-body-map-explorer": dynamic(() => import("../kalapurusha-body-map-explorer").then(m => ({ default: m.KalapurushaBodyMapExplorer }))),
  "known-illness-support-consultation-trainer": dynamic(() => import("../known-illness-support-consultation-trainer").then(m => ({ default: m.KnownIllnessSupportConsultationTrainer }))),
  "kp-property-fourth-cusp-sub-lord-lab": dynamic(() => import("../kp-property-fourth-cusp-sub-lord-lab").then(m => ({ default: m.KpPropertyFourthCuspSubLordLab }))),
  "kp-property-significator-timing-lab": dynamic(() => import("../kp-property-significator-timing-lab").then(m => ({ default: m.KpPropertySignificatorTimingLab }))),
  "kp-education-cuspal-sub-lord-lab": dynamic(() => import("../kp-education-cuspal-sub-lord-lab").then(m => ({ default: m.KpEducationCuspalSubLordLab }))),
  "kp-education-significator-hierarchy-lab": dynamic(() => import("../kp-education-significator-hierarchy-lab").then(m => ({ default: m.KpEducationSignificatorHierarchyLab }))),
  "kp-education-exam-timing-overlay-lab": dynamic(() => import("../kp-education-exam-timing-overlay-lab").then(m => ({ default: m.KpEducationExamTimingOverlayLab }))),
  "kp-education-worked-exam-synthesis-lab": dynamic(() => import("../kp-education-worked-exam-synthesis-lab").then(m => ({ default: m.KpEducationWorkedExamSynthesisLab }))),
  "kp-cuspal-sub-lord-doctrine": dynamic(() => import("../kp-cuspal-sub-lord-doctrine").then(m => ({ default: m.KpCuspalSubLordDoctrine }))),
  "kp-money-significators-evaluator": dynamic(() => import("../kp-money-significators-evaluator").then(m => ({ default: m.KpMoneySignificatorsEvaluator }))),
  "kp-investment-timing-explorer": dynamic(() => import("../kp-investment-timing-explorer").then(m => ({ default: m.KpInvestmentTimingExplorer }))),
  "kp-wealth-question-workbench": dynamic(() => import("../kp-wealth-question-workbench").then(m => ({ default: m.KpWealthQuestionWorkbench }))),
  "karaka-pollution-seventh-workbench": dynamic(() => import("../karaka-pollution-seventh-workbench").then(m => ({ default: m.KarakaPollutionSeventhWorkbench }))),
  "kp-seventh-csl-marriage-promise-workbench": dynamic(() => import("../kp-seventh-csl-marriage-promise-workbench").then(m => ({ default: m.KpSeventhCslMarriagePromiseWorkbench }))),
  "kp-seventh-significator-delivery-workbench": dynamic(() => import("../kp-seventh-significator-delivery-workbench").then(m => ({ default: m.KpSeventhSignificatorDeliveryWorkbench }))),
  "kp-marriage-significator-dasha-window": dynamic(() => import("../kp-marriage-significator-dasha-window").then(m => ({ default: m.KpMarriageSignificatorDashaWindow }))),
  "kp-marriage-question-verdict-lab": dynamic(() => import("../kp-marriage-question-verdict-lab").then(m => ({ default: m.KpMarriageQuestionVerdictLab }))),
};
