import dynamic from "next/dynamic";

export const REGISTRY = {
  "sloka-recitation-frame": dynamic(() => import("../sloka-recitation-frame").then(m => ({ default: m.SlokaRecitationFrame }))),
  "shukla-tithi-strip": dynamic(() => import("../shukla-tithi-strip").then(m => ({ default: m.ShuklaTithiStrip }))),
  "santana-fifth-house-significations-compass": dynamic(() => import("../santana-fifth-house-significations-compass").then(m => ({ default: m.SantanaFifthHouseSignificationsCompass }))),
  "santana-fifth-lord-permutations-wheel": dynamic(() => import("../santana-fifth-lord-permutations-wheel").then(m => ({ default: m.SantanaFifthLordPermutationsWheel }))),
  "santana-fifth-drishti-balance": dynamic(() => import("../santana-fifth-drishti-balance").then(m => ({ default: m.SantanaFifthDrishtiBalance }))),
  "santana-obstruction-honesty-workbench": dynamic(() => import("../santana-obstruction-honesty-workbench").then(m => ({ default: m.SantanaObstructionHonestyWorkbench }))),
  "saptamsha-builder-wheel": dynamic(() => import("../saptamsha-builder-wheel").then(m => ({ default: m.SaptamshaBuilderWheel }))),
  "study-abroad-theme-timing-synthesis": dynamic(() => import("../study-abroad-theme-timing-synthesis").then(m => ({ default: m.StudyAbroadThemeTimingSynthesis }))),
  "scope-of-competence-router": dynamic(() => import("../scope-of-competence-router").then(m => ({ default: m.ScopeOfCompetenceRouter }))),
  "sixth-house-litigation-profile": dynamic(() => import("../sixth-house-litigation-profile").then(m => ({ default: m.SixthHouseLitigationProfile }))),
  "sixth-house-dusthana-upachaya-paradox": dynamic(() => import("../sixth-house-dusthana-upachaya-paradox").then(m => ({ default: m.SixthHouseDusthanaUpachayaParadox }))),
  "sixth-lord-permutations-litigation": dynamic(() => import("../sixth-lord-permutations-litigation").then(m => ({ default: m.SixthLordPermutationsLitigation }))),
  "saturn-delay-structure-persistence-litigation": dynamic(() => import("../saturn-delay-structure-persistence-litigation").then(m => ({ default: m.SaturnDelayStructurePersistenceLitigation }))),
  "synthesis-statement-composition-discipline": dynamic(() => import("../synthesis-statement-composition-discipline").then(m => ({ default: m.SynthesisStatementCompositionDiscipline }))),
  "stream-orientation-leak-audit-lab": dynamic(() => import("../stream-orientation-leak-audit-lab").then(m => ({ default: m.StreamOrientationLeakAuditLab }))),
  "sarasvati-yoga-checklist-workbench": dynamic(() => import("../sarasvati-yoga-checklist-workbench").then(m => ({ default: m.SarasvatiYogaChecklistWorkbench }))),
  "second-house-wealth-evaluator": dynamic(() => import("../second-house-wealth-evaluator").then(m => ({ default: m.SecondHouseWealthEvaluator }))),
  "second-eleventh-lord-permutations": dynamic(() => import("../second-eleventh-lord-permutations").then(m => ({ default: m.SecondEleventhLordPermutations }))),
  "seventh-house-marriage-profile-workbench": dynamic(() => import("../seventh-house-marriage-profile-workbench").then(m => ({ default: m.SeventhHouseMarriageProfileWorkbench }))),
  "seventh-lord-placement-reader": dynamic(() => import("../seventh-lord-placement-reader").then(m => ({ default: m.SeventhLordPlacementReader }))),
  "seventh-aspect-net-workbench": dynamic(() => import("../seventh-aspect-net-workbench").then(m => ({ default: m.SeventhAspectNetWorkbench }))),
  "sixth-house-disease-recovery-workbench": dynamic(() => import("../sixth-house-disease-recovery-workbench").then(m => ({ default: m.SixthHouseDiseaseRecoveryWorkbench }))),
  "secondary-property-indicators-synthesis-lab": dynamic(() => import("../secondary-property-indicators-synthesis-lab").then(m => ({ default: m.SecondaryPropertyIndicatorsSynthesisLab }))),
};
