import dynamic from "next/dynamic";

export const REGISTRY = {
  "lineage-matters-synthesis-dojo": dynamic(() => import("../lineage-matters-synthesis-dojo").then(m => ({ default: m.LineageMattersSynthesisDojo }))),
  "litigation-confidence-synthesis": dynamic(() => import("../litigation-confidence-synthesis").then(m => ({ default: m.LitigationConfidenceSynthesis }))),
  "lawyer-substitution-refusal-router": dynamic(() => import("../lawyer-substitution-refusal-router").then(m => ({ default: m.LawyerSubstitutionRefusalRouter }))),
  "litigation-scope-competence-closer": dynamic(() => import("../litigation-scope-competence-closer").then(m => ({ default: m.LitigationScopeCompetenceCloser }))),
  "longevity-method-selector": dynamic(() => import("../longevity-method-selector").then(m => ({ default: m.LongevityMethodSelector }))),
  "longevity-ethics-response-trainer": dynamic(() => import("../longevity-ethics-response-trainer").then(m => ({ default: m.LongevityEthicsResponseTrainer }))),
  "lal-kitab-career-overlay-workbench": dynamic(() => import("../lal-kitab-career-overlay-workbench").then(m => ({ default: m.LalKitabCareerOverlayWorkbench }))),
  "lunar-yoga-detector": dynamic(() => import("../lunar-yoga-detector").then(m => ({ default: m.LunarYogaDetector }))),
  "lakshmi-saraswati-detector": dynamic(() => import("../lakshmi-saraswati-detector").then(m => ({ default: m.LakshmiSaraswatiDetector }))),
  "lal-kitab-tradition-explorer": dynamic(() => import("../lal-kitab-tradition-explorer").then(m => ({ default: m.LalKitabTraditionExplorer }))),
  "lal-kitab-farman-timeline": dynamic(() => import("../lal-kitab-farman-timeline").then(m => ({ default: m.LalKitabFarmanTimeline }))),
  "lal-kitab-classical-comparator": dynamic(() => import("../lal-kitab-classical-comparator").then(m => ({ default: m.LalKitabClassicalComparator }))),
  "lal-kitab-status-and-ethics-explorer": dynamic(() => import("../lal-kitab-status-and-ethics-explorer").then(m => ({ default: m.LalKitabStatusAndEthicsExplorer }))),
  "lal-kitab-teva-doctrine-explorer": dynamic(() => import("../lal-kitab-teva-doctrine-explorer").then(m => ({ default: m.LalKitabTevaDoctrineExplorer }))),
  "lal-kitab-luminary-mapper": dynamic(() => import("../lal-kitab-luminary-mapper").then(m => ({ default: m.LalKitabLuminaryMapper }))),
  "lal-kitab-mars-mercury-mapper": dynamic(() => import("../lal-kitab-mars-mercury-mapper").then(m => ({ default: m.LalKitabMarsMercuryMapper }))),
  "lal-kitab-benefic-sorter": dynamic(() => import("../lal-kitab-benefic-sorter").then(m => ({ default: m.LalKitabBeneficSorter }))),
  "lal-kitab-shadow-triad": dynamic(() => import("../lal-kitab-shadow-triad").then(m => ({ default: m.LalKitabShadowTriad }))),
  "lal-kitab-varshphala-concept": dynamic(() => import("../lal-kitab-varshphala-concept").then(m => ({ default: m.LalKitabVarshphalaConcept }))),
  "lal-kitab-varshphala-computation": dynamic(() => import("../lal-kitab-varshphala-computation").then(m => ({ default: m.LalKitabVarshphalaComputation }))),
  "lal-kitab-varshphala-reading": dynamic(() => import("../lal-kitab-varshphala-reading").then(m => ({ default: m.LalKitabVarshphalaReading }))),
  "lal-kitab-tajika-varshaphala-comparator": dynamic(() => import("../lal-kitab-tajika-varshaphala-comparator").then(m => ({ default: m.LalKitabTajikaVarshaphalaComparator }))),
  "lal-kitab-upaya-family-sorter": dynamic(() => import("../lal-kitab-upaya-family-sorter").then(m => ({ default: m.LalKitabUpayaFamilySorter }))),
  "lal-kitab-epistemic-disclosure-lab": dynamic(() => import("../lal-kitab-epistemic-disclosure-lab").then(m => ({ default: m.LalKitabEpistemicDisclosureLab }))),
  "lal-kitab-remedy-decision-framework": dynamic(() => import("../lal-kitab-remedy-decision-framework").then(m => ({ default: m.LalKitabRemedyDecisionFramework }))),
  "lal-kitab-recognition-lab": dynamic(() => import("../lal-kitab-recognition-lab").then(m => ({ default: m.LalKitabRecognitionLab }))),
  "lal-kitab-stream-mastery-map": dynamic(() => import("../lal-kitab-stream-mastery-map").then(m => ({ default: m.LalKitabStreamMasteryMap }))),
  "lagna-assessment-scorer": dynamic(() => import("../lagna-assessment-scorer").then(m => ({ default: m.LagnaAssessmentScorer }))),
  "layered-framework-decision-synthesis": dynamic(() => import("../layered-framework-decision-synthesis").then(m => ({ default: m.LayeredFrameworkDecisionSynthesis }))),
  "lal-kitab-remedy-augmentation-lab": dynamic(() => import("../lal-kitab-remedy-augmentation-lab").then(m => ({ default: m.LalKitabRemedyAugmentationLab }))),
  "lal-kitab-property-teva-formula-lab": dynamic(() => import("../lal-kitab-property-teva-formula-lab").then(m => ({ default: m.LalKitabPropertyTevaFormulaLab }))),
  "lakshmi-yoga-analyser": dynamic(() => import("../lakshmi-yoga-analyser").then(m => ({ default: m.LakshmiYogaAnalyser }))),
  "lal-kitab-money-formula-revisited": dynamic(() => import("../lal-kitab-money-formula-revisited").then(m => ({ default: m.LalKitabMoneyFormulaRevisited }))),
  "lal-kitab-money-planets-analyser": dynamic(() => import("../lal-kitab-money-planets-analyser").then(m => ({ default: m.LalKitabMoneyPlanetsAnalyser }))),
  "lal-kitab-loss-formulas-evaluator": dynamic(() => import("../lal-kitab-loss-formulas-evaluator").then(m => ({ default: m.LalKitabLossFormulasEvaluator }))),
  "lal-kitab-wealth-reading-workbench": dynamic(() => import("../lal-kitab-wealth-reading-workbench").then(m => ({ default: m.LalKitabWealthReadingWorkbench }))),
  "lal-kitab-graha-clusters": dynamic(() => import("../lal-kitab-graha-clusters").then(m => ({ default: m.LalKitabGrahaClusters }))),
  "lagna-contributor-note": dynamic(() => import("../lagna-contributor-note").then(m => ({ default: m.LagnaContributorNote }))),
  "lal-kitab-upaya-intro": dynamic(() => import("../lal-kitab-upaya-intro").then(m => ({ default: m.LalKitabUpayaIntro }))),
  "lagna-suddhi-evaluator": dynamic(() => import("../lagna-suddhi-evaluator").then(m => ({ default: m.LagnaSuddhiEvaluator }))),
};
