import dynamic from "next/dynamic";

export const REGISTRY = {
  "panchanga-five-limb-framework": dynamic(() => import("../panchanga-five-limb-framework").then(m => ({ default: m.PanchangaFiveLimbFramework }))),
  "panchaka-cancellation": dynamic(() => import("../panchaka-cancellation").then(m => ({ default: m.PanchakaCancellation }))),
  "pythagorean-letter-table-explorer": dynamic(() => import("../pythagorean-letter-table-explorer").then(m => ({ default: m.PythagoreanLetterTableExplorer }))),
  "putra-karaka-pk-convergence-bench": dynamic(() => import("../putra-karaka-pk-convergence-bench").then(m => ({ default: m.PutraKarakaPkConvergenceBench }))),
  "pk-placement-navamsha-workbench": dynamic(() => import("../pk-placement-navamsha-workbench").then(m => ({ default: m.PkPlacementNavamshaWorkbench }))),
  "pcpndt-refusal-trainer": dynamic(() => import("../pcpndt-refusal-trainer").then(m => ({ default: m.PcpndtRefusalTrainer }))),
  "permanent-settlement-synthesis": dynamic(() => import("../permanent-settlement-synthesis").then(m => ({ default: m.PermanentSettlementSynthesis }))),
  "predictive-karma-profile": dynamic(() => import("../predictive-karma-profile").then(m => ({ default: m.PredictiveKarmaProfile }))),
  "purva-ashadha-relationship-map": dynamic(() => import("../purva-ashadha-relationship-map").then(m => ({ default: m.PurvaAshadhaRelationshipMap }))),
  "purva-uttara-doctrine-explorer": dynamic(() => import("../purva-uttara-doctrine-explorer").then(m => ({ default: m.PurvaUttaraDoctrineExplorer }))),
  "pushya-auspiciousness-lab": dynamic(() => import("../pushya-auspiciousness-lab").then(m => ({ default: m.PushyaAuspiciousnessLab }))),
  "pada-calculator": dynamic(() => import("../pada-calculator").then(m => ({ default: m.PadaCalculator }))),
  "pada-navamsha-mapper": dynamic(() => import("../pada-navamsha-mapper").then(m => ({ default: m.PadaNavamshaMapper }))),
  "pmpy-detector": dynamic(() => import("../pmpy-detector").then(m => ({ default: m.PmpyDetector }))),
  "pmpy-archetype-explorer": dynamic(() => import("../pmpy-archetype-explorer").then(m => ({ default: m.PmpyArchetypeExplorer }))),
  "pmpy-dilution-checker": dynamic(() => import("../pmpy-dilution-checker").then(m => ({ default: m.PmpyDilutionChecker }))),
  "pmpy-grade-scenario": dynamic(() => import("../pmpy-grade-scenario").then(m => ({ default: m.PmpyGradeScenario }))),
  "pancha-mahapurusha-career-workbench": dynamic(() => import("../pancha-mahapurusha-career-workbench").then(m => ({ default: m.PanchaMahapurushaCareerWorkbench }))),
  "paksha-yuddha-calculator": dynamic(() => import("../paksha-yuddha-calculator").then(m => ({ default: m.PakshaYuddhaCalculator }))),
  "pitr-dosha-indicator": dynamic(() => import("../pitr-dosha-indicator").then(m => ({ default: m.PitrDoshaIndicator }))),
  "positive-argala-2-4-11": dynamic(() => import("../positive-argala-2-4-11").then(m => ({ default: m.PositiveArgala2411 }))),
  "planetary-state-synthesizer": dynamic(() => import("../planetary-state-synthesizer").then(m => ({ default: m.PlanetaryStateSynthesizer }))),
  "personal-year-calculator": dynamic(() => import("../personal-year-calculator").then(m => ({ default: m.PersonalYearCalculator }))),
  "parashara-default-explorer": dynamic(() => import("../parashara-default-explorer").then(m => ({ default: m.ParasharaDefaultExplorer }))),
  "prediction-confidence-dial": dynamic(() => import("../prediction-confidence-dial").then(m => ({ default: m.PredictionConfidenceDial }))),
  "parashara-anchor-md1-lab": dynamic(() => import("../parashara-anchor-md1-lab").then(m => ({ default: m.ParasharaAnchorMd1Lab }))),
  "parashara-only-statement-template-lab": dynamic(() => import("../parashara-only-statement-template-lab").then(m => ({ default: m.ParasharaOnlyStatementTemplateLab }))),
  "parashara-worked-reading-md1-lab": dynamic(() => import("../parashara-worked-reading-md1-lab").then(m => ({ default: m.ParasharaWorkedReadingMd1Lab }))),
  "parashara-anchor-not-verdict-lab": dynamic(() => import("../parashara-anchor-not-verdict-lab").then(m => ({ default: m.ParasharaAnchorNotVerdictLab }))),
  "parashara-kp-two-stream-statement-lab": dynamic(() => import("../parashara-kp-two-stream-statement-lab").then(m => ({ default: m.ParasharaKpTwoStreamStatementLab }))),
  "parashara-kp-jaimini-three-stream-lab": dynamic(() => import("../parashara-kp-jaimini-three-stream-lab").then(m => ({ default: m.ParasharaKpJaiminiThreeStreamLab }))),
  "property-dasha-acquisition-timing-lab": dynamic(() => import("../property-dasha-acquisition-timing-lab").then(m => ({ default: m.PropertyDashaAcquisitionTimingLab }))),
  "property-competence-routing-lab": dynamic(() => import("../property-competence-routing-lab").then(m => ({ default: m.PropertyCompetenceRoutingLab }))),
  "predictive-failure-mode-quiz": dynamic(() => import("../predictive-failure-mode-quiz").then(m => ({ default: m.PredictiveFailureModeQuiz }))),
  "preliminary-cross-check-preflight": dynamic(() => import("../preliminary-cross-check-preflight").then(m => ({ default: m.PreliminaryCrossCheckPreflight }))),
  "parashari-kp-verifier": dynamic(() => import("../parashari-kp-verifier").then(m => ({ default: m.ParashariKpVerifier }))),
  "prarabdha-illustration": dynamic(() => import("../prarabdha-illustration").then(m => ({ default: m.PrarabdhaIllustration }))),
  "protective-discipline-checklist": dynamic(() => import("../protective-discipline-checklist").then(m => ({ default: m.ProtectiveDisciplineChecklist }))),
  "puja-vrata-guide": dynamic(() => import("../puja-vrata-guide").then(m => ({ default: m.PujaVrataGuide }))),
  "planet-sub-lord-modulator": dynamic(() => import("../planet-sub-lord-modulator").then(m => ({ default: m.PlanetSubLordModulator }))),
  "proposal-evaluation-synthesis-lab": dynamic(() => import("../proposal-evaluation-synthesis-lab").then(m => ({ default: m.ProposalEvaluationSynthesisLab }))),
  "post-tier-1-reading-list": dynamic(() => import("../post-tier-1-reading-list").then(m => ({ default: m.PostTier1ReadingList }))),
  "practitioner-pledge": dynamic(() => import("../practitioner-pledge").then(m => ({ default: m.PractitionerPledgeSimulator }))),
  "path-forward": dynamic(() => import("../path-forward").then(m => ({ default: m.PathForwardRoadmap }))),
};
