import dynamic from "next/dynamic";

export const REGISTRY = {
  "rahu-kala-yamaganda-explorer": dynamic(() => import("../rahu-kala-yamaganda-explorer").then(m => ({ default: m.RahuKalaYamagandaExplorer }))),
  "rashi-navamsha-pair": dynamic(() => import("../rashi-navamsha-pair").then(m => ({ default: m.RashiNavamshaPair }))),
  "rahu-foreign-boundary-explorer": dynamic(() => import("../rahu-foreign-boundary-explorer").then(m => ({ default: m.RahuForeignBoundaryExplorer }))),
  "rahu-placement-permutations-explorer": dynamic(() => import("../rahu-placement-permutations-explorer").then(m => ({ default: m.RahuPlacementPermutationsExplorer }))),
  "rahu-dasha-timing-explorer": dynamic(() => import("../rahu-dasha-timing-explorer").then(m => ({ default: m.RahuDashaTimingExplorer }))),
  "rahu-aspect-doctrine-fork-explorer": dynamic(() => import("../rahu-aspect-doctrine-fork-explorer").then(m => ({ default: m.RahuAspectDoctrineForkExplorer }))),
  "rudra-maheshvara-workbench": dynamic(() => import("../rudra-maheshvara-workbench").then(m => ({ default: m.RudraMaheshvaraWorkbench }))),
  "revati-constellation-diagram": dynamic(() => import("../revati-constellation-diagram").then(m => ({ default: m.RevatiConstellationDiagram }))),
  "rashi-drishti-grid": dynamic(() => import("../rashi-drishti-grid").then(m => ({ default: m.RashiDrishtiGrid }))),
  "raja-yoga-detector": dynamic(() => import("../raja-yoga-detector").then(m => ({ default: m.RajaYogaDetector }))),
  "raja-yoga-tenth-career-workbench": dynamic(() => import("../raja-yoga-tenth-career-workbench").then(m => ({ default: m.RajaYogaTenthCareerWorkbench }))),
  "raja-yoga-variants-map": dynamic(() => import("../raja-yoga-variants-map").then(m => ({ default: m.RajaYogaVariantsMap }))),
  "raja-yoga-worked-example": dynamic(() => import("../raja-yoga-worked-example").then(m => ({ default: m.RajaYogaWorkedExample }))),
  "raja-dhana-overlap-map": dynamic(() => import("../raja-dhana-overlap-map").then(m => ({ default: m.RajaDhanaOverlapMap }))),
  "ruchaka-valour-simulator": dynamic(() => import("../ruchaka-valour-simulator").then(m => ({ default: m.RuchakaValourSimulator }))),
  "rashi-drishti-visualizer": dynamic(() => import("../rashi-drishti-visualizer").then(m => ({ default: m.RashiDrishtiVisualizer }))),
  "rashi-drishti-mapper": dynamic(() => import("../rashi-drishti-mapper").then(m => ({ default: m.RashiDrishtiMapper }))),
  "remedy-year-decision-tree": dynamic(() => import("../remedy-year-decision-tree").then(m => ({ default: m.RemedyYearDecisionTree }))),
  "reading-synthesis-workbench": dynamic(() => import("../reading-synthesis-workbench").then(m => ({ default: m.ReadingSynthesisWorkbench }))),
  "reading-documentation-template": dynamic(() => import("../reading-documentation-template").then(m => ({ default: m.ReadingDocumentationTemplate }))),
  "reduction-order-demo": dynamic(() => import("../reduction-order-demo").then(m => ({ default: m.ReductionOrderDemo }))),
  "remedy-authority-map": dynamic(() => import("../remedy-authority-map").then(m => ({ default: m.RemedyAuthorityMap }))),
  "remedy-matching-explorer": dynamic(() => import("../remedy-matching-explorer").then(m => ({ default: m.RemedyMatchingExplorer }))),
  "restraint-doctrine-card": dynamic(() => import("../restraint-doctrine-card").then(m => ({ default: m.RestraintDoctrineCard }))),
  "ruling-planets-role-explorer": dynamic(() => import("../ruling-planets-role-explorer").then(m => ({ default: m.RulingPlanetsRoleExplorer }))),
  "ruling-planets-calculator": dynamic(() => import("../ruling-planets-calculator").then(m => ({ default: m.RulingPlanetsCalculator }))),
  "ruling-planets-confirmation-workbench": dynamic(() => import("../ruling-planets-confirmation-workbench").then(m => ({ default: m.RulingPlanetsConfirmationWorkbench }))),
  "reader-due-diligence": dynamic(() => import("../reader-due-diligence").then(m => ({ default: m.ReaderDueDiligence }))),
  "reasonable-fees": dynamic(() => import("../reasonable-fees").then(m => ({ default: m.ReasonableFees }))),
};
