import dynamic from "next/dynamic";

export const REGISTRY = {
  "amatyakaraka-career-workbench": dynamic(() => import("../amatyakaraka-career-workbench").then(m => ({ default: m.AmatyakarakaCareerWorkbench }))),
  "atmakaraka-king-lens": dynamic(() => import("../atmakaraka-king-lens").then(m => ({ default: m.AtmakarakaKingLens }))),
  "atmakaraka-saturn-king-lens-lab": dynamic(() => import("../atmakaraka-saturn-king-lens-lab").then(m => ({ default: m.AtmakarakaSaturnKingLensLab }))),
  "amk-tenth-lord-comparison-workbench": dynamic(() => import("../amk-tenth-lord-comparison-workbench").then(m => ({ default: m.AmkTenthLordComparisonWorkbench }))),
  "ayur-calculator": dynamic(() => import("../ayur-calculator").then(m => ({ default: m.AyurCalculator }))),
  "anuradha-devotion-network": dynamic(() => import("../anuradha-devotion-network").then(m => ({ default: m.AnuradhaDevotionNetwork }))),
  "ashlesha-honest-handling-dojo": dynamic(() => import("../ashlesha-honest-handling-dojo").then(m => ({ default: m.AshleshaHonestHandlingDojo }))),
  "antardasha-table-builder": dynamic(() => import("../antardasha-table-builder").then(m => ({ default: m.AntardashaTableBuilder }))),
  "ashtottari-explorer": dynamic(() => import("../ashtottari-explorer").then(m => ({ default: m.AshtottariExplorer }))),
  "ashtottari-condition-checker": dynamic(() => import("../ashtottari-condition-checker").then(m => ({ default: m.AshtottariConditionChecker }))),
  "amk-placement-navamsha-workbench": dynamic(() => import("../amk-placement-navamsha-workbench").then(m => ({ default: m.AmkPlacementNavamshaWorkbench }))),
  "aspect-doctrine-comparator": dynamic(() => import("../aspect-doctrine-comparator").then(m => ({ default: m.AspectDoctrineComparator }))),
  "akhanda-samrajya-checker": dynamic(() => import("../akhanda-samrajya-checker").then(m => ({ default: m.AkhandaSamrajyaChecker }))),
  "argala-explorer": dynamic(() => import("../argala-explorer").then(m => ({ default: m.ArgalaExplorer }))),
  "argala-concept-explorer": dynamic(() => import("../argala-concept-explorer").then(m => ({ default: m.ArgalaConceptExplorer }))),
  "arudha-pada-finder": dynamic(() => import("../arudha-pada-finder").then(m => ({ default: m.ArudhaPadaFinder }))),
  "arudha-pada-calculator": dynamic(() => import("../arudha-pada-calculator").then(m => ({ default: m.ArudhaPadaCalculator }))),
  "arudha-pada-explorer": dynamic(() => import("../arudha-pada-explorer").then(m => ({ default: m.ArudhaPadaExplorer }))),
  "arudha-caveat-lab": dynamic(() => import("../arudha-caveat-lab").then(m => ({ default: m.ArudhaCaveatLab }))),
  "ak-drishti-synthesizer": dynamic(() => import("../ak-drishti-synthesizer").then(m => ({ default: m.AkDrishtiSynthesizer }))),
  "active-medical-distress-handling-trainer": dynamic(() => import("../active-medical-distress-handling-trainer").then(m => ({ default: m.ActiveMedicalDistressHandlingTrainer }))),
  "aptitude-tendency-mapper": dynamic(() => import("../aptitude-tendency-mapper").then(m => ({ default: m.AptitudeTendencyMapper }))),
  "ayanamsha-choice-verifier": dynamic(() => import("../ayanamsha-choice-verifier").then(m => ({ default: m.AyanamshaChoiceVerifier }))),
  "ashtakavarga-intro": dynamic(() => import("../ashtakavarga-intro").then(m => ({ default: m.AshtakavargaIntro }))),
  "ashtakavarga-contributors": dynamic(() => import("../ashtakavarga-contributors").then(m => ({ default: m.AshtakavargaContributors }))),
  "ashtakavarga-stream-map": dynamic(() => import("../ashtakavarga-stream-map").then(m => ({ default: m.AshtakavargaStreamMap }))),
  "ashta-kuta-framework-workbench": dynamic(() => import("../ashta-kuta-framework-workbench").then(m => ({ default: m.AshtaKutaFrameworkWorkbench }))),
  "ashta-kuta-score-interpretation-workbench": dynamic(() => import("../ashta-kuta-score-interpretation-workbench").then(m => ({ default: m.AshtaKutaScoreInterpretationWorkbench }))),
  "agastya-flow": dynamic(() => import("../agastya-flow").then(m => ({ default: m.AgastyaFlow }))),
};
