// AUTO-GENERATED by scripts/split-interactive-map.js — do not edit.
export const map: Record<string, () => Promise<any>> = {
  "dasha-conflict-timing-sweep": () => import("./dasha-conflict-timing-sweep/index"),
  "kp-case-outcome-horary-intro": () => import("./kp-case-outcome-horary-intro/index"),
  "kp-litigation-cusp-tool": () => import("./kp-litigation-cusp-tool/index"),
  "kp-litigation-synthesis-workbench": () => import("./kp-litigation-synthesis-workbench/index"),
  "kp-shared-significator-explorer": () => import("./kp-shared-significator-explorer/index"),
  "lawyer-substitution-refusal-router": () => import("./lawyer-substitution-refusal-router/index"),
  "litigation-confidence-synthesis": () => import("./litigation-confidence-synthesis/index"),
  "litigation-scope-competence-closer": () => import("./litigation-scope-competence-closer/index"),
  "mars-contest-karaka-litigation": () => import("./mars-contest-karaka-litigation/index"),
  "mars-saturn-dynamic-explorer": () => import("./mars-saturn-dynamic-explorer/index"),
  "mars-saturn-litigation-synthesis": () => import("./mars-saturn-litigation-synthesis/index"),
  "mars-saturn-relationship-distinguisher": () => import("./mars-saturn-relationship-distinguisher/index"),
  "saturn-delay-structure-persistence-litigation": () => import("./saturn-delay-structure-persistence-litigation/index"),
  "sixth-house-dusthana-upachaya-paradox": () => import("./sixth-house-dusthana-upachaya-paradox/index"),
  "sixth-house-litigation-profile": () => import("./sixth-house-litigation-profile/index"),
  "sixth-lord-permutations-litigation": () => import("./sixth-lord-permutations-litigation/index"),
};
