// AUTO-GENERATED by scripts/split-interactive-map.js — do not edit.
export const map: Record<string, () => Promise<any>> = {
  "boundary-crossing-demonstrator": () => import("./boundary-crossing-demonstrator/index"),
  "chart-planet-positioner": () => import("./chart-planet-positioner/index"),
  "quadrant-triad-visualizer": () => import("./quadrant-triad-visualizer/index"),
  "rashi-attribute-wheel": () => import("./rashi-attribute-wheel/index"),
  "rashi-boundary-wheel": () => import("./rashi-boundary-wheel/index"),
  "rashi-modality-classifier": () => import("./rashi-modality-classifier/index"),
  "rashi-profile-explorer": () => import("./rashi-profile-explorer/index"),
  "rashi-rising-classifier": () => import("./rashi-rising-classifier/index"),
  "rashi-stream-comparator": () => import("./rashi-stream-comparator/index"),
  "trikona-pair-explorer": () => import("./trikona-pair-explorer/index"),
};
