// AUTO-GENERATED by scripts/split-interactive-map.js — do not edit.
//
// Each entry lazily loads a per-module map (~25 entries) instead of the
// monolithic 1,077-entry interactive-map. This reduces lesson page
// cold-compile from ~2.5min to ~10-15s.

type ModuleMap = Record<string, () => Promise<any>>;

const registry: Record<string, () => Promise<{ map: ModuleMap }>> = {
  "tier-1/module-1": () => import("./tier-1/module-1/_map"),
  "tier-1/module-10": () => import("./tier-1/module-10/_map"),
  "tier-1/module-11": () => import("./tier-1/module-11/_map"),
  "tier-1/module-12": () => import("./tier-1/module-12/_map"),
  "tier-1/module-13": () => import("./tier-1/module-13/_map"),
  "tier-1/module-14": () => import("./tier-1/module-14/_map"),
  "tier-1/module-15": () => import("./tier-1/module-15/_map"),
  "tier-1/module-16": () => import("./tier-1/module-16/_map"),
  "tier-1/module-17": () => import("./tier-1/module-17/_map"),
  "tier-1/module-18": () => import("./tier-1/module-18/_map"),
  "tier-1/module-19": () => import("./tier-1/module-19/_map"),
  "tier-1/module-2": () => import("./tier-1/module-2/_map"),
  "tier-1/module-20": () => import("./tier-1/module-20/_map"),
  "tier-1/module-21": () => import("./tier-1/module-21/_map"),
  "tier-1/module-22": () => import("./tier-1/module-22/_map"),
  "tier-1/module-23": () => import("./tier-1/module-23/_map"),
  "tier-1/module-24": () => import("./tier-1/module-24/_map"),
  "tier-1/module-3": () => import("./tier-1/module-3/_map"),
  "tier-1/module-4": () => import("./tier-1/module-4/_map"),
  "tier-1/module-5": () => import("./tier-1/module-5/_map"),
  "tier-1/module-6": () => import("./tier-1/module-6/_map"),
  "tier-1/module-7": () => import("./tier-1/module-7/_map"),
  "tier-1/module-8": () => import("./tier-1/module-8/_map"),
  "tier-1/module-9": () => import("./tier-1/module-9/_map"),
  "tier-2/module-01": () => import("./tier-2/module-01/_map"),
  "tier-2/module-02": () => import("./tier-2/module-02/_map"),
  "tier-2/module-03": () => import("./tier-2/module-03/_map"),
  "tier-2/module-04": () => import("./tier-2/module-04/_map"),
  "tier-2/module-05": () => import("./tier-2/module-05/_map"),
  "tier-2/module-06": () => import("./tier-2/module-06/_map"),
  "tier-2/module-07": () => import("./tier-2/module-07/_map"),
  "tier-2/module-08": () => import("./tier-2/module-08/_map"),
  "tier-2/module-09": () => import("./tier-2/module-09/_map"),
  "tier-2/module-10": () => import("./tier-2/module-10/_map"),
  "tier-2/module-11": () => import("./tier-2/module-11/_map"),
  "tier-2/module-12": () => import("./tier-2/module-12/_map"),
  "tier-2/module-13": () => import("./tier-2/module-13/_map"),
  "tier-2/module-14": () => import("./tier-2/module-14/_map"),
  "tier-2/module-15": () => import("./tier-2/module-15/_map"),
  "tier-2/module-16": () => import("./tier-2/module-16/_map"),
  "tier-2/module-17": () => import("./tier-2/module-17/_map"),
  "tier-2/module-18": () => import("./tier-2/module-18/_map"),
  "tier-2/module-19": () => import("./tier-2/module-19/_map"),
  "tier-2/module-20": () => import("./tier-2/module-20/_map"),
  "tier-2/module-21": () => import("./tier-2/module-21/_map"),
  "tier-2/module-22": () => import("./tier-2/module-22/_map"),
};

/**
 * Load a single interactive component by tier-module key and component slug.
 * Only the ~25 imports for the specific module are processed by webpack,
 * not all 1,077.
 */
export async function loadInteractive(
  tierModule: string,
  componentKey: string
): Promise<any | null> {
  const mapLoader = registry[tierModule];
  if (!mapLoader) return null;
  const { map } = await mapLoader();
  const componentLoader = map[componentKey];
  if (!componentLoader) return null;
  try {
    return await componentLoader();
  } catch (err) {
    console.error(`Failed to load interactive ${tierModule}/${componentKey}`, err);
    return null;
  }
}
