// AUTO-GENERATED by scripts/split-interactive-map.js — do not edit.
export const map: Record<string, () => Promise<unknown>> = {
  "career-case-1-job-offer-evaluation": () => import("./career-case-1-job-offer-evaluation/index"),
  "career-case-2-entrepreneurship-vs-employment-decision": () => import("./career-case-2-entrepreneurship-vs-employment-decision/index"),
  "career-case-3-mid-career-pivot-timing": () => import("./career-case-3-mid-career-pivot-timing/index"),
  "career-case-4-government-vs-private-sector-aptitude-reading": () => import("./career-case-4-government-vs-private-sector-aptitude-reading/index"),
  "career-case-5-ambiguous-chart-with-honest-inconclusive-output": () => import("./career-case-5-ambiguous-chart-with-honest-inconclusive-output/index"),
  "marriage-case-1-when-will-i-marry-question": () => import("./marriage-case-1-when-will-i-marry-question/index"),
  "marriage-case-2-proposal-evaluation-with-manglik-defusion": () => import("./marriage-case-2-proposal-evaluation-with-manglik-defusion/index"),
  "marriage-case-3-ashta-kuta-low-score-but-favourable-multi-stream-synthesis": () => import("./marriage-case-3-ashta-kuta-low-score-but-favourable-multi-stream-synthesis/index"),
  "marriage-case-4-couple-with-existing-marriage-difficulty-question": () => import("./marriage-case-4-couple-with-existing-marriage-difficulty-question/index"),
  "marriage-case-5-second-marriage-question-with-ethical-framing": () => import("./marriage-case-5-second-marriage-question-with-ethical-framing/index"),
};
