// AUTO-GENERATED by scripts/split-interactive-map.js — do not edit.
export const map: Record<string, () => Promise<any>> = {
  "dasha-timing-foreign-settlement-sweep": () => import("./dasha-timing-foreign-settlement-sweep/index"),
  "kp-foreign-travel-cusp-tool": () => import("./kp-foreign-travel-cusp-tool/index"),
  "ninth-house-chart-t1-explorer": () => import("./ninth-house-chart-t1-explorer/index"),
  "nri-yoga-citation-honesty-explorer": () => import("./nri-yoga-citation-honesty-explorer/index"),
  "nri-yoga-pattern-spotter": () => import("./nri-yoga-pattern-spotter/index"),
  "permanent-settlement-synthesis": () => import("./permanent-settlement-synthesis/index"),
  "rahu-aspect-doctrine-fork-explorer": () => import("./rahu-aspect-doctrine-fork-explorer/index"),
  "rahu-dasha-timing-explorer": () => import("./rahu-dasha-timing-explorer/index"),
  "rahu-foreign-boundary-explorer": () => import("./rahu-foreign-boundary-explorer/index"),
  "rahu-placement-permutations-explorer": () => import("./rahu-placement-permutations-explorer/index"),
  "scope-of-competence-router": () => import("./scope-of-competence-router/index"),
  "study-abroad-theme-timing-synthesis": () => import("./study-abroad-theme-timing-synthesis/index"),
  "twelfth-house-chart-t1-explorer": () => import("./twelfth-house-chart-t1-explorer/index"),
  "twelve-nine-three-arc-explorer": () => import("./twelve-nine-three-arc-explorer/index"),
  "twelve-nine-three-aspect-explorer": () => import("./twelve-nine-three-aspect-explorer/index"),
  "visa-question-multi-causal-synthesis": () => import("./visa-question-multi-causal-synthesis/index"),
};
